#!/bin/bash
#PBS -l nodes=1:ppn=9:xk
#PBS -l walltime=40:00:00
#PBS -N image_ranking_
#PBS -e \$PBS_JOBID.err
#PBS -o \$PBS_JOBID.out
# -m and -M set up mail messages at begin,end,abort:
# -m bea
# -M nms9@illinois.edu

#. /opt/modules/default/init/bash
module load python/2.0.0
#module load cudatoolkit
cd ~/scratch/34_1/image_ranking/
aprun -n 1 -N 1 python test.py --start_epoch 11 --resnet 34 --batch_size 12
